"""Conversation-local constraint parsing for Slice 2."""

from backend.conversation.constraints import (
    ConstraintField,
    ConstraintHardness,
    ConstraintOperation,
    ConstraintOperator,
    ConstraintPatch,
    ConstraintProvenance,
    NormalizedConstraint,
    NormalizedConstraintStatus,
    normalize_constraint_patch,
    normalize_constraint_patches,
    parse_constraint_patches,
)
from backend.conversation.state import (
    ConfirmedTargetContext,
    ConversationState,
    InMemoryConversationStateRepository,
    PendingSwitchEffect,
    PendingSwitchTrigger,
    PendingTargetSwitch,
    StateChangeType,
    StateDiff,
    StateDiffEntry,
    StateTransitionRequest,
    StateTransitionResult,
    StateTransitionStatus,
    reduce_conversation_state,
)
from backend.conversation.target_resolution import (
    ComparisonMember,
    ContextAction,
    ResolutionSource,
    TargetResolution,
    TurnTarget,
    TurnTargetKind,
)

__all__ = [
    "ConstraintField",
    "ConstraintHardness",
    "ConstraintOperation",
    "ConstraintOperator",
    "ConstraintPatch",
    "ConstraintProvenance",
    "ConfirmedTargetContext",
    "ConversationState",
    "NormalizedConstraint",
    "NormalizedConstraintStatus",
    "InMemoryConversationStateRepository",
    "PendingSwitchEffect",
    "PendingSwitchTrigger",
    "PendingTargetSwitch",
    "StateChangeType",
    "StateDiff",
    "StateDiffEntry",
    "StateTransitionRequest",
    "StateTransitionResult",
    "StateTransitionStatus",
    "normalize_constraint_patch",
    "normalize_constraint_patches",
    "parse_constraint_patches",
    "reduce_conversation_state",
    "ComparisonMember",
    "ContextAction",
    "ResolutionSource",
    "TargetResolution",
    "TurnTarget",
    "TurnTargetKind",
]
